spring:
  application:
    name: cloud-service-seller
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZoone: http://localhost:8761/eureka
server:
  port: 7040